import type { Metadata } from "next";
import { poppins } from "@/fonts/monospace";
import "./globals.css";
import Nav from "@/components/Nav";
import Footer from "@/components/Footer";

export const metadata: Metadata = {
  title: "Gudi Developer",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${poppins.className} font-[500] antialiased bg-[#202020] text-white`}
      >
        <Nav />
        {children}
        <Footer />
      </body>
    </html>
  );
}
