POST http://localhost:3000/checkWord
Content-Type: application/json

{
  "palabra": "perro",
  "intento": "epeee"
}

###
GET http://localhost:3000/users

###
POST http://localhost:3000/users
Content-Type: application/json

{
  "nombre": "Felipe",
  "puntos": "134",
  "tiempo": "05:43"
}

###
DELETE http://localhost:3000/users/8

###
GET http://localhost:3000/users/8